using System;
using Exercicio03;
Pessoa pessoa1 = new Pessoa();
pessoa1.Nome = "Pedro";
pessoa1.Idade = 17;
Console.WriteLine("Dados da pessoa:");
pessoa1.ExibirDados();
pessoa1.AlterarIdade(35);
Console.WriteLine("Dados da pessoa após alteração de idade:");
pessoa1.ExibirDados();
Console.WriteLine($"");
Console.WriteLine($"");
Pessoa pessoa2 = new Pessoa();
pessoa2.Nome = "Davi";
pessoa2.Idade = 14;
Console.WriteLine("Dados da pessoa:");
pessoa2.ExibirDados();
pessoa2.AlterarIdade(-5); 
Console.WriteLine("Dados da pessoa após tentativa de alteração de idade:");
pessoa2.ExibirDados();